# Generated by Django 5.1.6 on 2025-06-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_created_at_candidate_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='gender_restriction',
            field=models.CharField(choices=[('any', 'Any Gender'), ('male', 'Male Only'), ('female', 'Female Only')], default='any', help_text='Restrict this position to specific gender', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
