# Generated by Django 5.1.6 on 2025-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_position_gender_restriction_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('junior', 'Junior Award'), ('senior', 'Senior Award')], default='senior', help_text='The type of position', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='is_nominated',
            field=models.BooleanField(default=False, help_text='Indicates if the student has been nominated for a position'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the student has verified their account'),
        ),
    ]
