# Generated by Django 5.1.6 on 2025-09-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_election_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='type',
        ),
    ]
