# Generated by Django 5.1.6 on 2025-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_remove_election_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('specific', 'Specific')], default='general', max_length=10),
        ),
    ]
