# Generated by Django 5.1.6 on 2025-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_election_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_nominated',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_changed_password',
            field=models.BooleanField(default=False, help_text='Indicates if the student has changed password at least once'),
        ),
    ]
