# Generated by Django 5.1.6 on 2025-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_student_is_nominated_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='alias',
            field=models.CharField(blank=True, help_text='Optional alias or nickname for the candidate', max_length=100, null=True),
        ),
    ]
